### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by antonyflour** [lmartire/DoApp#3]
- [x] migliorare report finale

- [x] migliorare activity iniziale

- [x] fare in modo da recuperare sempre il Component anche se non riportato nell'eccezione

- [x] gestire getAppPID per pid multipli (caso musical.ly)

- [ ] migliorare documentazione

- [x] migliorare la listview della scelta della target app

- [x] sistemare test case per PathPrefix
